### GENERAL SETTINGS ###

# Site settings
title: Forward Command Post
description: "Forward Command Post is a group dedicated to improving the gaming experience, currently focused on Team Fortress 2."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://fwdcp.net"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: steam
    url: http://steamcommunity.com/groups/fwdcp
  - title: github
    url: http://github.com/fwdcp
  - title: trello
    url: https://trello.com/forwardcommandpost
  - title: paypal
    url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZJAZP9L4A6RHJ

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
# address:
  # - lines:
    # -
email: forwardcommandpost@gmail.com
# tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: thesupremecommander
    position: Founder & Developer
    text: thesupremecommander is distinguished for his passion, dedication, experience, and skill, which when combined become a potent force allowing him to seek out solutions to novel and complex technical problems.
    img: thesupremecommander.jpg
    social:
      - title: steam
        url: http://steamcommunity.com/id/thesupremecommander
      - title: envelope
        url: mailto:thesupremecmdr@gmail.com
      - title: github
        url: http://github.com/thesupremecommander
      - title: twitter
        url: http://twitter.com/thesupremecmdr
      - title: twitch
        url: http://twitch.tv/thesupremecommander
  - name: Ness 'uberchain' Delacroix
    position: Artist & Animator
    text: uberchain comes from a strong background of illustration and design with tenacity and enthusiasm - a zeal that contributes to her video editing, animation, and graphic design talents.
    img: uberchain.png
    social:
      - title: steam
        url: http://steamcommunity.com/id/spameidareyou
      - title: deviantart
        url: http://uberchain.deviantart.com
      - title: tumblr
        url: http://uberchain.tumblr.com
      - title: twitter
        url: http://twitter.com/uberchain
      - title: youtube
        url: http://youtube.com/uberchainyt

# Partners information. Shown on Home and About pages.
partners:
  - name: TeamFortressTV
    img: teamfortresstv.png
    social:
      - title: external-link
        url: http://teamfortress.tv

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Forward Command Post is a group dedicated to improving the gaming experience, currently focused on Team Fortress 2."

# Testimonial content. Shown on Home and About page.
# testimonial:
    # message:
    # author:
    # position:
