title: Forward Command Post
description: "Forward Command Post is a group dedicated to improving the gaming experience, currently focused on Team Fortress 2."
baseurl: ""
url: "http://fwdcp.net"

markdown: kramdown

collections:
  members:
    output: true
    permalink: /members/:path/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: projects
    values:
      layout: project

social:
  - type: github
    title: GitHub
    url: https://github.com/fwdcp
  - type: steam
    title: Steam
    url: https://steamcommunity.com/groups/fwdcp
  - type: twitter
    title: Twitter
    url: https://twitter.com/fwdcp_
